// Sport icon mapping - maps sport event IDs to their icon filenames
export const SPORT_ICONS: Record<number, string> = {
  4: 'cricket.svg',
  1: 'football.svg',
  2: 'tennis.svg',
  8: 'table-tennis.svg',
  68: 'esoccer.svg',
  10: 'horse-racing.svg',
  65: 'greyhound-racing.svg',
  15: 'basketball.svg',
  69: 'wrestling.svg',
  18: 'volleyball.svg',
  22: 'badminton.svg',
  59: 'snooker.svg',
  57: 'darts.svg',
  6: 'boxing.svg',
  3: 'mixed-martial-arts.svg',
  58: 'american-football.svg',
  11: 'e-games.svg',
  19: 'ice-hockey.svg',
  9: 'futsal.svg',
  40: 'politics.svg',
  67: 'boat-racing.svg',
  52: 'motor-sports.svg',
  12: 'greyhounds.svg',
  66: 'kabaddi.svg',
  5: 'golf.svg',
  55: 'rugby-league.svg',
  7: 'beach-volleyball.svg',
  13: 'trotting.svg',
  39: 'handball.svg',
  14: 'speedway.svg',
  16: 'motogp.svg',
  17: 'chess.svg',
  20: 'equine-sports.svg',
  21: 'australian-rules.svg',
  23: 'formula-1.svg',
  24: 'nascar.svg',
  25: 'hockey.svg',
  26: 'supercars.svg',
  27: 'netball.svg',
  28: 'surfing.svg',
  29: 'cycling.svg',
  30: 'gaelic-sports.svg',
  31: 'biathlon.svg',
  32: 'motorbikes.svg',
  33: 'athletics.svg',
  34: 'squash.svg',
  35: 'basketball-3x3.svg',
  36: 'floorball.svg',
  37: 'sumo.svg',
  38: 'virtual-sports.svg',
  41: 'weather.svg',
  42: 'tv-games.svg',
  43: 'lottery.svg',
  44: 'bowls.svg',
  45: 'poker.svg',
  46: 'waterpolo.svg',
  47: 'alpine-skiing.svg',
  48: 'sailing.svg',
  49: 'hurling.svg',
  50: 'ski-jumping.svg',
  51: 'bandy.svg',
  53: 'baseball.svg',
  54: 'rugby-union.svg',
  56: 'curling.svg',
  60: 'gaelic-games.svg',
  61: 'lottery-specials.svg',
  62: 'soccer.svg',
  63: 'special-bets.svg',
  64: 'esports.svg',
};

// Helper function to get icon path for a sport
export const getSportIcon = (eventId: number): string => {
  const iconFile = SPORT_ICONS[eventId];
  return iconFile ? `/icons/sports/${iconFile}` : '/icons/sports/football.svg'; // fallback to football
};

// Helper function to get icon component props
export const getSportIconProps = (eventId: number) => {
  return {
    src: getSportIcon(eventId),
    alt: `Sport ${eventId} icon`,
    className: 'sport-icon',
  };
};
