// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Read from environment variables (from .env file)
export const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://rgrmozpakutydlvxxngt.supabase.co";
export const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJncm1venBha3V0eWRsdnh4bmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNjEzNTUsImV4cCI6MjA4NTYzNzM1NX0.-ZojFwp1lf2BhmfelGhfTc0-EDquUOSHUvrA5WiMqKI";

console.log("[Supabase] Connecting to:", SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Singleton pattern to prevent multiple instances during HMR
const createSupabaseClient = () =>
  createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });

export const supabase = (window as any)._supabase || createSupabaseClient();

if (import.meta.env.DEV) {
  (window as any)._supabase = supabase;
}
