// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const SUPABASE_URL = "https://puqfxuisuqtnpgxfsyhe.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cWZ4dWlzdXF0bnBneGZzeWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxNjEwMzcsImV4cCI6MjA4MjczNzAzN30.eIakI_8NLPJoqVTueT-8pwYziIUdc3Vvury1pDeJguA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Singleton pattern to prevent multiple instances during HMR
const createSupabaseClient = () =>
  createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

export const supabase = (window as any)._supabase || createSupabaseClient();

if (import.meta.env.DEV) {
  (window as any)._supabase = supabase;
}
